# From https://github.com/actions/starter-workflows

name: Run tests (and linting?)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pytest
        # Cannot install **private** dependencies unless we add ssh key?
        # Anyway, for now we have no real tests.
        # python -m pip install -e .
        pip install $(./.parse_requirements.py)
    - name: Test with pytest
      run: |
        pytest
